FROM node:18-alpine AS builder

ARG DB_URI
ARG JWT_SECRET

ENV DB_URI=${DB_URI}
ENV JWT_SECRET=${JWT_SECRET}

WORKDIR /app

COPY api/shop-api/package*.json tsconfig.json ./

RUN npm install

COPY api/shop-api/src/ ./src/

RUN npm run build

FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./

EXPOSE 3000

CMD ["npm", "run", "start:prod"]