name: CI/CD - Shop-En-Nuage

env:
  REGISTRY: shopennuage.azurecr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches: ['main']

permissions:
  contents: read
  id-token: write

jobs:
  test:
    name: API Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install Dependencies
        run: |
          cd api/shop-api
          npm install
      
      - name: Run Tests
        run: |
          cd api/shop-api
          npm test

  build-and-publish-docker-image:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
      
      - name: Extract Docker Metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/shop-en-nuage
          tags: |
            type=sha,format=long
            type=ref,event=branch
            type=semver,pattern={{version}}
      
      - name: Build and Publish Docker Image
        id: publish
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/dockerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

  deploy-image-to-app-service:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    needs: build-and-publish-docker-image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Set Environment Variables on Azure App Service
        run: |
          az webapp config appsettings set \
            --name 'shop-en-nuage-app' \
            --resource-group 'MyResourceGroup' \
            --settings DB_URI=${{ secrets.DB_URI }} JWT_SECRET=${{ secrets.JWT_SECRET }}
      
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'shop-en-nuage-app'
          images: ${{ env.REGISTRY }}/shop-en-nuage:${{ github.sha }}
        env:
          DB_URI: ${{ secrets.DB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}